# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5083c4d8425b99acca1eb2c13cd39c46dd6a7faaf443c1aadef44b4e3700e1acc7f4349f13b8769a72bacd31fb5ab71c704e1e5f1208061cec033d4cbf70ea0e

test:
  secret_key_base: ee1dfba258bdc93afdb72ae61a6e78ac6288d1ff7951f5df5dc709c5b8e4c45891f6172d67ac833623a07b05285398dcc8b9c742cd2c237a077ea5d90d21a38f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
